os: osx
osx_image: xcode10.1
language: swift
xcode_destination: platform=iOS Simulator,OS=12.0,name=iPhone XS
script: xcodebuild clean build test -project HelloDependency.xcodeproj -scheme "IOSDependencyContainer" -sdk iphonesimulator12.1 CODE_SIGN_IDENTITY="" CODE_SIGN_REQUIRED=NO
